### ISSUE TITLE
You forgot to add dependencies to your package.json

### ISSUE THREAD

**Issue by jjcastano** [serenity-frontstack/angular-basic#1]
I've download your starter kit and, at least at master branch, it does not work "as is".
You forgot to add "yargs" and "gulp-if" as dev dependencies so.. when you try to run "gulp serve" an error will be shown and the execution will stop.

After that, I've notice another issue with the gulp version you encourage to use. I'll open another issue with that.

I hope it helps!! ;)

**Comment by jcdevelopmentspain** [comment]
Hi @jjcastano !

Thank you for your contribution.

The dependencies that you mention in the issue, "yargs" and "gulp-if" have been updated  and the issue solved! :)
