### ISSUE TITLE
What gulp version must we use?

### ISSUE THREAD

**Issue by jjcastano** [serenity-frontstack/angular-basic#2]
I've installed "gulp" as a global package, updated at the latest version (3.9.1) as shown on npmjs.org.

When executing "gulp serve", an error ocurred (I've added it at the bottom)

To fix this problem I must run gulp serve with the same version as you propose on your package.json:

> "gulp": "gulpjs/gulp#4ed9a4a3275559c73a396eff7e1fde3824951ebb", 

If that is correct and you encourage us to use that version, maybe you'll need to explain it at readme or be sure your code runs with the actual version

The error shown:

> C:\datos\adh\repos\front\www>gulp serve
> [18:08:27] Loading C:\datos\adh\repos\front\www\gulp\appconfig.js
> [18:08:28] Loading C:\datos\adh\repos\front\www\gulp\assets.js
> [18:08:28] Loading C:\datos\adh\repos\front\www\gulp\browsersync.js
> [18:08:28] Loading C:\datos\adh\repos\front\www\gulp\build.js
> [18:08:31] Loading C:\datos\adh\repos\front\www\gulp\e2e-test.js
> [18:08:31] Loading C:\datos\adh\repos\front\www\gulp\inject.js
> [18:08:31] Loading C:\datos\adh\repos\front\www\gulp\karma.js
> [18:08:33] Loading C:\datos\adh\repos\front\www\gulp\misc.js
> [18:08:34] Loading C:\datos\adh\repos\front\www\gulp\ngdocs.js
> [18:08:35] Loading C:\datos\adh\repos\front\www\gulp\partials.js
> [18:08:35] Loading C:\datos\adh\repos\front\www\gulp\scripts.js
> [18:08:35] Loading C:\datos\adh\repos\front\www\gulp\styles.js
> [18:08:35] Using gulpfile C:\datos\adh\repos\front\www\gulpfile.js
> c:\Users\xxx\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:129
>     gulpInst.start.apply(gulpInst, toRun);
>                   ^
> 
> TypeError: Cannot read property 'apply' of undefined
>     at c:\Users\n70135\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:129:19
>     at nextTickCallbackWith0Args (node.js:420:9)
>     at process._tickCallback (node.js:349:13)
>     at Function.Module.runMain (module.js:443:11)
>     at startup (node.js:139:18)
>     at node.js:968:3

I hope it helps!! ;)

**Comment by jcdevelopmentspain** [comment]
Hi @jjcastano !

First of all, thank you for your contribution,

According to your issue, **Gulp-cli** is needed globally, while gulp will be refered locally. This configuration allows to use differents gulp versions in each project. README.md contains more details about this installation.

Furthermore, even though the version of Gulp in the npmjs repository indicate 3.9.1, Gulp team is working actively in the release of their current Gulp 4.
This version brings important features improving Gulp 3:

(https://github.com/gulpjs/gulp/blob/4.0/CHANGELOG.md)

This update fix problems around the tasks sequencer which didn’t allow to configure which tasks are dependent on others and how to have some tasks in parallel among others.
 
At the time to write this comment, Gulp4 release looks imminent (https://github.com/gulpjs/gulp/milestones)


Thank you again for your support !

**Comment by jjcastano** [comment]
Thanks for your fast support!!
I'll try that configuration ;)

One more question: I asume that configuration will work fine locally. Have you tried on Serenity ALM continuos deployment??

Thanks again!!
