### ISSUE TITLE
Error executing gulp test when there's no test

### ISSUE THREAD

**Issue by jjcastano** [serenity-frontstack/angular-basic#4]
Hello!!

This is a minor bug ;)

When you have no tests on your project and configure the threshold to 0, you have the following error:

> 15 09 2016 15:27:06.360:INFO [PhantomJS 2.1.1 (Windows 7 0.0.0)]: Connected on socket /#5bXOOdKHN6aQqVr-AAAA with id 91787885
> PhantomJS 2.1.1 (Windows 7 0.0.0): Executed 0 of 0 ERROR (0.006 secs / 0 secs)
> [15:27:06] 'karma:single-run' errored after 3.11 s
> [15:27:06] Error: Failed 1 tests.
>     at C:\datos\adh\repos\evol-front\gulp\karma.js:17:43
>     at removeAllListeners (C:\datos\adh\repos\evol-front\node_modules\karma\lib\server.js:336:7)
>     at Server.<anonymous> (C:\datos\adh\repos\evol-front\node_modules\karma\lib\server.js:347:9)
>     at Server.g (events.js:260:16)
>     at emitNone (events.js:72:20)
>     at Server.emit (events.js:166:7)
>     at emitCloseNT (net.js:1537:8)
>     at nextTickCallbackWith1Arg (node.js:431:9)
>     at process._tickDomainCallback (node.js:394:17)
> [15:27:06] 'test' errored after 4.68 s

If you executed 0 of 0 tests.. How it's possible to have failed 1 tests?? :p

**Comment by DvdChavarri** [comment]
This is a reported Karma issue that can be adjusted with failOnEmptyTestSuite parameter in the karma configuration file. It has been update and released in the new version v1.2.3
For more information: https://github.com/karma-runner/karma/issues/926
Thanks for noticing.
